<?php

namespace App\Support;

/**
 * Locale-aware URL helper. Routes are registered per locale with names suffixed
 * by locale (e.g. "about.id" / "about.en"), so URLs are generated by base name
 * + locale rather than a single {locale} parameter.
 */
class Localize
{
    /** Build a URL for a locale-suffixed route: url('about', 'id') => route('about.id'). */
    public static function url(string $name, ?string $locale = null, array $params = []): string
    {
        $locale = $locale ?: app()->getLocale();

        return route("{$name}.{$locale}", $params);
    }

    /** Strip the ".id"/".en" suffix from a route name: base('about.id') => 'about'. */
    public static function base(?string $routeName): ?string
    {
        return $routeName ? preg_replace('/\.(id|en)$/', '', $routeName) : null;
    }
}
